### ISSUE TITLE
SCP wrapper doesn't check for the "BASTION_CONF_FILE" env var

### ISSUE THREAD

**Issue by Krenodeno** [ovh/the-bastion-ansible-wrapper#20]
Hi,

I just saw that `scpwrapper.py` doesn't check the presence of the bastion vars via a config file that path would be overridden by that `BASTION_CONF_FILE` like `sshwrapper.py` does. That means the SCP wrapper doesn't support that way of configuring the wrapper.

The code ranges to copy are [line 18](https://github.com/ovh/the-bastion-ansible-wrapper/blob/main/sshwrapper.py#L18), and [line 42](https://github.com/ovh/the-bastion-ansible-wrapper/blob/main/sshwrapper.py#L42) to [line 50](https://github.com/ovh/the-bastion-ansible-wrapper/blob/main/sshwrapper.py#L50) from `sshwrapper.py`

**Comment by Krenodeno** [comment]
Also, the use of `BASTION_CONF_FILE` is not mentioned [here](https://github.com/ovh/the-bastion-ansible-wrapper#using-vars-from-a-config-file)

**Comment by jriouovh** [comment]
Thank you for this report. It's now fixed.
